import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from "@/components/analytics";
import { ModeToggle } from "@/components/mode-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-2xl mx-auto py-10 px-4">
            <header className="mb-10">
              <div className="flex items-center justify-between">
                <h1 className="text-2xl font-bold">
                  <Link href="/">stevy.dev</Link>
                </h1>
                <div className="flex items-center gap-4">
                  <nav className="l-auto text-sm font-medium space-x-6">
                    <Link href="/tech">Tech</Link>
                    <Link href="/essay">Essay</Link>
                    <Link href="/about">About</Link>
                  </nav>
                  <ModeToggle />
                </div>
              </div>
            </header>
            <main>{children}</main>
            <footer className="mt-10 text-center">
              <p className="text-sm text-slate-500">
                stevy.dev &copy; {new Date().getFullYear()}
              </p>
            </footer>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
